In [29]:
import cv2
# from matplotlib import pyplot as plt
cap = cv2.VideoCapture(0, cv2.CAP_DSHOW) # this is the magic!

resx,resy = 1920,1080
cap.set(cv2.CAP_PROP_FRAME_WIDTH, resx )
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, resy)

r, frame = cap.read()
frame.shape

(1080, 1920, 3)

In [30]:
cap.release()

In [9]:
xcenter=int(resx/2)
ycenter=660
yoffset = 325
xoffset = 450

In [14]:
cv2.imshow('crop',frame[ycenter-yoffset:ycenter+yoffset,xcenter-xoffset:xcenter+xoffset])

: 

In [31]:
cv2.imshow('adsf',frame)

In [32]:

import cv2

img = cv2.imread('/Users/mustafa/test.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

plt.imshow(gray)

error: OpenCV(3.4.9) ..\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


In [33]:
import numpy as np

In [5]:
resy = 1080
np.linspace(0,resy,30)

array([   0.        ,   37.24137931,   74.48275862,  111.72413793,
        148.96551724,  186.20689655,  223.44827586,  260.68965517,
        297.93103448,  335.17241379,  372.4137931 ,  409.65517241,
        446.89655172,  484.13793103,  521.37931034,  558.62068966,
        595.86206897,  633.10344828,  670.34482759,  707.5862069 ,
        744.82758621,  782.06896552,  819.31034483,  856.55172414,
        893.79310345,  931.03448276,  968.27586207, 1005.51724138,
       1042.75862069, 1080.        ])

In [8]:
1080/29

37.241379310344826

In [10]:
list(range(5)[::-1])

[4, 3, 2, 1, 0]

In [12]:
float(False)

0.0

In [16]:
from funkshuns import *
flattenList(
    [[a,a+10 ]for a in range(2)]
)

ModuleNotFoundError: No module named 'funkshuns'

In [18]:
from __future__ import division
import os
import cv2
import dlib
# from .eye import Eye
# from .calibration import Calibration

In [34]:
frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

In [35]:
frame.shape

(1080, 1920)

In [36]:
# from __future__ import division
# import os
# import cv2
# import dlib
# from .eye import Eye
# from .calibration import Calibration



# _face_detector is used to detect faces
_face_detector = dlib.get_frontal_face_detector()

# _predictor is used to get facial landmarks of a given face
# cwd = os.path.abspath(os.path.dirname(__file__))
# model_path = os.path.abspath(os.path.join(cwd, "trained_models/shape_predictor_68_face_landmarks.dat"))
model_path=r'C:\app\GazeTracking\gaze_tracking\trained_models\shape_predictor_68_face_landmarks.dat'
_predictor = dlib.shape_predictor(model_path)

faces = _face_detector(frame)

if len(faces):
    landmarks = _predictor(frame, faces[0])

In [45]:
pupl = [0,1]
np.array(pupl).reshape(2,1).T

array([[0, 1]])

In [46]:
a = np.array([[0,1,2],
[3,4,5]])
b = np.array([[9],[10]])
np.concatenate([a,b],1)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [50]:
np.stack([a.T , a.T+1]).shape

(2, 3, 2)

In [51]:
import cv2

In [52]:
cv2.__version__

'3.4.9'

In [4]:
from pathlib import Path
import pandas as pd, numpy as np
-np.ones((478,3))

(478, 3)

In [3]:
pth = Path.cwd()/'data'
trainx = np.load(pth/'trainx.npy')
trainx

array([[[ 0.5611136 ,  0.71059871, -0.04667135],
        [ 0.56394976,  0.64846879, -0.06666785],
        [ 0.56000954,  0.67279762, -0.04013636],
        ...,
        [ 0.6230697 ,  0.55399102,  0.03066162],
        [ 0.60948241,  0.56562901,  0.03066162],
        [ 0.619775  ,  0.58255666,  0.03066162]],

       [[ 0.54293382,  0.69979221, -0.04585708],
        [ 0.54676604,  0.63555318, -0.06539873],
        [ 0.54454124,  0.66125584, -0.0393954 ],
        ...,
        [ 0.61013895,  0.54651564,  0.02845671],
        [ 0.5962615 ,  0.55760485,  0.02845671],
        [ 0.60697305,  0.57384688,  0.02845671]],

       [[ 0.52122682,  0.69528329, -0.04703152],
        [ 0.51860744,  0.6247068 , -0.06370761],
        [ 0.51876062,  0.65236801, -0.03911404],
        ...,
        [ 0.59109581,  0.537328  ,  0.02256693],
        [ 0.57615423,  0.54928827,  0.02256693],
        [ 0.58812362,  0.56616104,  0.02256693]],

       ...,

       [[ 0.49077713,  0.69378161, -0.0503746 ],
        [ 0

In [26]:
trainx.shape

(14, 478, 3)

In [1]:
from pathlib import Path
import pandas as pd, numpy as np
import xarray as xr

In [4]:
trainx.shape

(14, 478, 3)

In [ ]:
trainx = xr.DataArray(trainx,dims=())

In [27]:
np.mean(trainx,axis=2)

array([[0.40834698, 0.3819169 , 0.39755693, ..., 0.40257411, 0.40192434,
        0.41099776],
       [0.39895632, 0.37230683, 0.38880056, ..., 0.3950371 , 0.39410769,
        0.40309221],
       [0.3898262 , 0.35986888, 0.3773382 , ..., 0.38366358, 0.38266981,
        0.39228386],
       ...,
       [0.37806138, 0.34968023, 0.36826829, ..., 0.37280292, 0.37294267,
        0.3823038 ],
       [0.3767355 , 0.34752528, 0.36619515, ..., 0.36478628, 0.36613438,
        0.37540251],
       [0.38591467, 0.35126591, 0.37136111, ..., 0.3612522 , 0.36261632,
        0.37210321]])

In [19]:
import random
a = [(np.array([1,2]),2),
(3,4),
(5,6)]
random.shuffle(a)
a

[(3, 4), (5, 6), (array([1, 2]), 2)]

In [7]:
np.random.randint(10,size=(2,4))

array([[1, 2, 3, 4],
       [7, 8, 7, 0]])

In [ ]:
conda create -n gaze -c conda-forge python=3.11
conda install -c conda-forge opencv
pip install mediapipe
pip install pyautogui
conda install -c conda-forge xarray

In [ ]:
        frame = cv2.cvtColor(self.frame, cv2.COLOR_BGR2GRAY)
        faces = self._face_detector(frame)

        if len(faces):
            landmarks = self._predictor(frame, faces[0])