 # run this manually on npy's if needed

In [47]:
from pathlib import Path
import pandas as pd, numpy as np
import  xarray as xr

In [65]:
pth = Path.cwd()/'data'
fullx = np.load(pth/'fullx.npy')
from pathlib import Path
import pandas as pd, numpy as np
import xarray as xr
pth
fullx.shape


(925, 478, 3)

In [67]:
pts = fullx[0]
pts.shape

(478, 3)

In [68]:
pts = xr.DataArray(pts,dims=('mark','crd'))
pts
assert len(pts['crd'])==3
pts['crd'] = ['x','y','z']
pts

<xarray.DataArray (mark: 478, crd: 3)>
array([[ 0.50624079,  0.68773794, -0.04679129],
       [ 0.50297022,  0.62405711, -0.06181955],
       [ 0.50503188,  0.65026665, -0.03873606],
       ...,
       [ 0.57461733,  0.53326344,  0.02171946],
       [ 0.56224507,  0.54703003,  0.02171946],
       [ 0.57448399,  0.56098342,  0.02171946]])
Coordinates:
  * crd      (crd) <U1 'x' 'y' 'z'
Dimensions without coordinates: mark

In [71]:
pts.transpose('crd','mark').shape

(3, 478)

In [72]:
xr.concat([pts],dim='s')

<xarray.DataArray (s: 1, mark: 478, crd: 3)>
array([[[ 0.50624079,  0.68773794, -0.04679129],
        [ 0.50297022,  0.62405711, -0.06181955],
        [ 0.50503188,  0.65026665, -0.03873606],
        ...,
        [ 0.57461733,  0.53326344,  0.02171946],
        [ 0.56224507,  0.54703003,  0.02171946],
        [ 0.57448399,  0.56098342,  0.02171946]]])
Coordinates:
  * crd      (crd) <U1 'x' 'y' 'z'
Dimensions without coordinates: s, mark

In [49]:
# shaep[::-1]

(3, 478)

In [52]:
 # x,y range 0-1
 # depth -x to x, with negative meaning closer to cam
 # normalize by centering on mean of face, and 


In [3]:
dimz = ('s','mark','crd')

In [4]:
shaep = (478,3) 

In [5]:
assert fullx.shape[1:] == shaep, fullx.shape

In [6]:
fullx

array([[[ 0.50624079,  0.68773794, -0.04679129],
        [ 0.50297022,  0.62405711, -0.06181955],
        [ 0.50503188,  0.65026665, -0.03873606],
        ...,
        [ 0.57461733,  0.53326344,  0.02171946],
        [ 0.56224507,  0.54703003,  0.02171946],
        [ 0.57448399,  0.56098342,  0.02171946]],

       [[ 0.58146489,  0.64478713, -0.04776418],
        [ 0.60196984,  0.59066093, -0.05829465],
        [ 0.59430254,  0.61998773, -0.03904247],
        ...,
        [ 0.63004708,  0.52681071,  0.05178811],
        [ 0.61782491,  0.5366528 ,  0.05178811],
        [ 0.62788451,  0.5510692 ,  0.05178811]],

       [[ 0.48626596,  0.79940629, -0.03541126],
        [ 0.47970462,  0.7405588 , -0.06511838],
        [ 0.48326707,  0.75842887, -0.03506269],
        ...,
        [ 0.55361837,  0.60129273,  0.00410048],
        [ 0.54166418,  0.61821908,  0.00410048],
        [ 0.55464506,  0.63392949,  0.00410048]],

       ...,

       [[ 0.56927377,  0.64986342, -0.05031385],
        [ 0

In [50]:
fullx = xr.DataArray(fullx,dims=dimz)
fullx

<xarray.DataArray (s: 925, mark: 478, crd: 3)>
array([[[ 0.50624079,  0.68773794, -0.04679129],
        [ 0.50297022,  0.62405711, -0.06181955],
        [ 0.50503188,  0.65026665, -0.03873606],
        ...,
        [ 0.57461733,  0.53326344,  0.02171946],
        [ 0.56224507,  0.54703003,  0.02171946],
        [ 0.57448399,  0.56098342,  0.02171946]],

       [[ 0.58146489,  0.64478713, -0.04776418],
        [ 0.60196984,  0.59066093, -0.05829465],
        [ 0.59430254,  0.61998773, -0.03904247],
        ...,
        [ 0.63004708,  0.52681071,  0.05178811],
        [ 0.61782491,  0.5366528 ,  0.05178811],
        [ 0.62788451,  0.5510692 ,  0.05178811]],

       [[ 0.48626596,  0.79940629, -0.03541126],
        [ 0.47970462,  0.7405588 , -0.06511838],
        [ 0.48326707,  0.75842887, -0.03506269],
        ...,
...
        ...,
        [ 0.62086117,  0.52158463,  0.04895424],
        [ 0.60940176,  0.53173256,  0.04895424],
        [ 0.61844212,  0.54696876,  0.04895424]],

       [[ 0.5272401 ,  0.67026985, -0.04908985],
        [ 0.53114569,  0.61064112, -0.06046974],
        [ 0.53033149,  0.63867074, -0.03952793],
        ...,
        [ 0.58499146,  0.5309273 ,  0.03701649],
        [ 0.57322448,  0.54407853,  0.03701649],
        [ 0.58421385,  0.557926  ,  0.03701649]],

       [[ 0.52998859,  0.64428031, -0.0488495 ],
        [ 0.53204745,  0.58934486, -0.0581761 ],
        [ 0.53119272,  0.61750561, -0.03889907],
        ...,
        [ 0.5835551 ,  0.51700771,  0.03846059],
        [ 0.57147408,  0.52966684,  0.03846059],
        [ 0.58288389,  0.54347062,  0.03846059]]])
Dimensions without coordinates: s, mark, crd

In [51]:
fullx['crd'] = ['x','y','z']
fullx

<xarray.DataArray (s: 925, mark: 478, crd: 3)>
array([[[ 0.50624079,  0.68773794, -0.04679129],
        [ 0.50297022,  0.62405711, -0.06181955],
        [ 0.50503188,  0.65026665, -0.03873606],
        ...,
        [ 0.57461733,  0.53326344,  0.02171946],
        [ 0.56224507,  0.54703003,  0.02171946],
        [ 0.57448399,  0.56098342,  0.02171946]],

       [[ 0.58146489,  0.64478713, -0.04776418],
        [ 0.60196984,  0.59066093, -0.05829465],
        [ 0.59430254,  0.61998773, -0.03904247],
        ...,
        [ 0.63004708,  0.52681071,  0.05178811],
        [ 0.61782491,  0.5366528 ,  0.05178811],
        [ 0.62788451,  0.5510692 ,  0.05178811]],

       [[ 0.48626596,  0.79940629, -0.03541126],
        [ 0.47970462,  0.7405588 , -0.06511838],
        [ 0.48326707,  0.75842887, -0.03506269],
        ...,
...
        ...,
        [ 0.62086117,  0.52158463,  0.04895424],
        [ 0.60940176,  0.53173256,  0.04895424],
        [ 0.61844212,  0.54696876,  0.04895424]],

       [[ 0.5272401 ,  0.67026985, -0.04908985],
        [ 0.53114569,  0.61064112, -0.06046974],
        [ 0.53033149,  0.63867074, -0.03952793],
        ...,
        [ 0.58499146,  0.5309273 ,  0.03701649],
        [ 0.57322448,  0.54407853,  0.03701649],
        [ 0.58421385,  0.557926  ,  0.03701649]],

       [[ 0.52998859,  0.64428031, -0.0488495 ],
        [ 0.53204745,  0.58934486, -0.0581761 ],
        [ 0.53119272,  0.61750561, -0.03889907],
        ...,
        [ 0.5835551 ,  0.51700771,  0.03846059],
        [ 0.57147408,  0.52966684,  0.03846059],
        [ 0.58288389,  0.54347062,  0.03846059]]])
Coordinates:
  * crd      (crd) <U1 'x' 'y' 'z'
Dimensions without coordinates: s, mark

In [45]:
fullxy['head'].isel(s=0).transpose('crd','mark')

<xarray.DataArray 'head' (crd: 3, mark: 478)>
array([[ 0.50624079,  0.50297022,  0.50503188, ...,  0.57461733,
         0.56224507,  0.57448399],
       [ 0.68773794,  0.62405711,  0.65026665, ...,  0.53326344,
         0.54703003,  0.56098342],
       [-0.04679129, -0.06181955, -0.03873606, ...,  0.02171946,
         0.02171946,  0.02171946]])
Coordinates:
  * crd      (crd) <U1 'x' 'y' 'z'
Dimensions without coordinates: mark

In [58]:
#  # transform to put the origin on the mean face pt position xy, and the closest depth
#  this array of 3 pts may be calibrated to new user/position
#  this is part of preprocessing before fed to model
#  # will need to be further scaled for keras but OK

In [52]:
xyz0 = xr.concat([
    fullx.mean(dim=['s','mark']).sel(crd=['x','y']) ,
    fullx.min(dim=['s','mark']).sel(crd=['z'])
],dim='crd')
xyz0

<xarray.DataArray (crd: 3)>
array([ 0.50771813,  0.66118333, -0.10227798])
Coordinates:
  * crd      (crd) <U1 'x' 'y' 'z'

In [73]:
pts

<xarray.DataArray (mark: 478, crd: 3)>
array([[ 0.50624079,  0.68773794, -0.04679129],
       [ 0.50297022,  0.62405711, -0.06181955],
       [ 0.50503188,  0.65026665, -0.03873606],
       ...,
       [ 0.57461733,  0.53326344,  0.02171946],
       [ 0.56224507,  0.54703003,  0.02171946],
       [ 0.57448399,  0.56098342,  0.02171946]])
Coordinates:
  * crd      (crd) <U1 'x' 'y' 'z'
Dimensions without coordinates: mark

In [ ]:
 # retrain without lower half face, then try

In [109]:
import matplotlib.pyplot as plt

In [105]:
a = 1
b = 2
a = b
b = 3
a

2

In [108]:
pts.values.copy()

array([[ 0.50624079,  0.68773794, -0.04679129],
       [ 0.50297022,  0.62405711, -0.06181955],
       [ 0.50503188,  0.65026665, -0.03873606],
       ...,
       [ 0.57461733,  0.53326344,  0.02171946],
       [ 0.56224507,  0.54703003,  0.02171946],
       [ 0.57448399,  0.56098342,  0.02171946]])

In [78]:
pts.isel({'mark':pupl}).values[:2]

array([0.57453156, 0.54718345])

In [97]:
pts.isel({'mark':slice(474,478)}).mean(dim='mark').values

array([5.08754191e-01, 6.32592681e-01, 6.16910766e-04])

In [104]:
pts.isel({'mark':slice(13,15)}).sel({'crd':'y'}).diff(dim='mark').values[0]

0.003964900970458984

In [ ]:
pupil = np.mean( [np.array([landmark.x,landmark.y]) for landmark in landmarks[474:478] ],axis=0)

In [92]:
pupil = pts.isel({'mark':pupl}).values[:2]
pupil

array([0.57453156, 0.54718345])

In [96]:
pupilcache = [ pupil,pupil+1,pupil+2]
np.stack(pupilcache,axis=0)
np.mean(pupilcache,axis=0)

array([1.57453156, 1.54718345])

In [74]:
pts - xyz0

<xarray.DataArray (mark: 478, crd: 3)>
array([[-0.00147734,  0.02655461,  0.05548669],
       [-0.00474791, -0.03712622,  0.04045843],
       [-0.00268624, -0.01091668,  0.06354192],
       ...,
       [ 0.0668992 , -0.12791989,  0.12399744],
       [ 0.05452694, -0.1141533 ,  0.12399744],
       [ 0.06676586, -0.10019991,  0.12399744]])
Coordinates:
  * crd      (crd) <U1 'x' 'y' 'z'
Dimensions without coordinates: mark

In [83]:
pos0 = np.array([0,0])
pos1 = np.array([3,4])
np.sqrt(np.sum((pos1-pos0)**2))


5.0

In [53]:
normx = fullx - xyz0
normx

<xarray.DataArray (s: 925, mark: 478, crd: 3)>
array([[[-0.00147734,  0.02655461,  0.05548669],
        [-0.00474791, -0.03712622,  0.04045843],
        [-0.00268624, -0.01091668,  0.06354192],
        ...,
        [ 0.0668992 , -0.12791989,  0.12399744],
        [ 0.05452694, -0.1141533 ,  0.12399744],
        [ 0.06676586, -0.10019991,  0.12399744]],

       [[ 0.07374676, -0.0163962 ,  0.0545138 ],
        [ 0.09425171, -0.0705224 ,  0.04398333],
        [ 0.08658441, -0.0411956 ,  0.06323551],
        ...,
        [ 0.12232896, -0.13437262,  0.15406609],
        [ 0.11010678, -0.12453053,  0.15406609],
        [ 0.12016638, -0.11011413,  0.15406609]],

       [[-0.02145217,  0.13822296,  0.06686672],
        [-0.02801351,  0.07937547,  0.0371596 ],
        [-0.02445106,  0.09724554,  0.06721529],
        ...,
...
        ...,
        [ 0.11314305, -0.1395987 ,  0.15123222],
        [ 0.10168364, -0.12945077,  0.15123222],
        [ 0.11072399, -0.11421457,  0.15123222]],

       [[ 0.01952197,  0.00908652,  0.05318813],
        [ 0.02342756, -0.05054221,  0.04180824],
        [ 0.02261337, -0.02251259,  0.06275005],
        ...,
        [ 0.07727333, -0.13025603,  0.13929447],
        [ 0.06550636, -0.1171048 ,  0.13929447],
        [ 0.07649573, -0.10325733,  0.13929447]],

       [[ 0.02227046, -0.01690302,  0.05342847],
        [ 0.02432932, -0.07183847,  0.04410188],
        [ 0.02347459, -0.04367772,  0.06337891],
        ...,
        [ 0.07583698, -0.14417562,  0.14073857],
        [ 0.06375595, -0.13151649,  0.14073857],
        [ 0.07516577, -0.11771271,  0.14073857]]])
Coordinates:
  * crd      (crd) <U1 'x' 'y' 'z'
Dimensions without coordinates: s, mark

In [54]:
# only for training data:
assert all(np.isclose(
    normx.mean(dim=['s','mark']).sel(crd=['x','y']).values,
    np.array([0,0])
)), normx.mean(dim=['s','mark']).sel(crd=['x','y'])

In [55]:
assert np.isclose( normx.min(dim=['s','mark']).sel(crd=['z']).values[0] , 0 ), \
    normx.min(dim=['s','mark']).sel(crd=['z'])

In [56]:
fully = np.load(pth/'fully.npy')
fully

array([[1067.5       ,  727.72727273],
       [2130.        ,  294.09090909],
       [ 855.        , 2342.5       ],
       ...,
       [2023.75      ,  294.09090909],
       [1598.75      ,  748.75      ],
       [1598.75      ,  536.25      ]])

In [57]:
assert fully.shape[-1]==2, f'should represent mouse x,y. hsape: {fully.shape}'

In [58]:
fully = xr.DataArray(fully,dims = ('s','pos'))
fully

<xarray.DataArray (s: 925, pos: 2)>
array([[1067.5       ,  727.72727273],
       [2130.        ,  294.09090909],
       [ 855.        , 2342.5       ],
       ...,
       [2023.75      ,  294.09090909],
       [1598.75      ,  748.75      ],
       [1598.75      ,  536.25      ]])
Dimensions without coordinates: s, pos

In [59]:
fully.name = 'mouse'
fully = fully.to_dataset()
fully

<xarray.Dataset>
Dimensions:  (s: 925, pos: 2)
Dimensions without coordinates: s, pos
Data variables:
    mouse    (s, pos) float64 1.068e+03 727.7 2.13e+03 ... 748.8 1.599e+03 536.2

In [60]:
normx.name = 'head'
normx = normx.to_dataset()
normx

<xarray.Dataset>
Dimensions:  (crd: 3, s: 925, mark: 478)
Coordinates:
  * crd      (crd) <U1 'x' 'y' 'z'
Dimensions without coordinates: s, mark
Data variables:
    head     (s, mark, crd) float64 -0.001477 0.02655 0.05549 ... -0.1177 0.1407

In [61]:
fullxy = xr.merge([normx,fully])
fullxy

<xarray.Dataset>
Dimensions:  (crd: 3, s: 925, mark: 478, pos: 2)
Coordinates:
  * crd      (crd) <U1 'x' 'y' 'z'
Dimensions without coordinates: s, mark, pos
Data variables:
    head     (s, mark, crd) float64 -0.001477 0.02655 0.05549 ... -0.1177 0.1407
    mouse    (s, pos) float64 1.068e+03 727.7 2.13e+03 ... 748.8 1.599e+03 536.2

In [63]:
fullxy.to_netcdf(pth/'fullxy.nc')

In [ ]:
--

In [35]:
fullx.min(dim=['s','mark']).sel(crd=['x','y'])

<xarray.DataArray (crd: 2)>
array([0.34123564, 0.4117589 ])
Coordinates:
  * crd      (crd) <U1 'x' 'y'

In [36]:
fullx.max(dim=['s','mark']).sel(crd=['x','y'])

<xarray.DataArray (crd: 2)>
array([0.67724437, 0.93402421])
Coordinates:
  * crd      (crd) <U1 'x' 'y'

In [37]:
fullx.min(dim=['s','mark']).sel(crd=['z'])

<xarray.DataArray (crd: 1)>
array([-0.08438877])
Coordinates:
  * crd      (crd) <U1 'z'

In [38]:
fullx.max(dim=['s','mark']).sel(crd=['z'])

<xarray.DataArray (crd: 1)>
array([0.17244691])
Coordinates:
  * crd      (crd) <U1 'z'

In [39]:
fullx.sel(crd=['x','y'])

<xarray.DataArray (s: 14, mark: 478, crd: 2)>
array([[[0.54249823, 0.75843912],
        [0.54515326, 0.69508421],
        [0.54141772, 0.71696281],
        ...,
        [0.61054242, 0.58184338],
        [0.59704584, 0.59593934],
        [0.60869378, 0.61394912]],

       [[0.51615345, 0.66109228],
        [0.50909269, 0.59273338],
        [0.51121944, 0.6262843 ],
        ...,
        [0.58229887, 0.52220255],
        [0.57105607, 0.53417051],
        [0.58244479, 0.54764807]],

       [[0.5428583 , 0.6875695 ],
        [0.54667181, 0.61982369],
        [0.54417199, 0.64853108],
        ...,
...
        ...,
        [0.57435524, 0.57684928],
        [0.56039917, 0.59063154],
        [0.57203752, 0.60885942]],

       [[0.58096111, 0.69058311],
        [0.58971399, 0.62311739],
        [0.58251387, 0.65146482],
        ...,
        [0.63466394, 0.55556518],
        [0.62326813, 0.5650515 ],
        [0.63252032, 0.57996458]],

       [[0.564852  , 0.65965652],
        [0.57037306, 0.59630448],
        [0.56558871, 0.62576789],
        ...,
        [0.62386042, 0.53909123],
        [0.6129148 , 0.54905093],
        [0.62309045, 0.56341213]]])
Coordinates:
  * crd      (crd) <U1 'x' 'y'
Dimensions without coordinates: s, mark

In [64]:
pts = np.load(pth/'fullx.npy')[0]
pts
pts.T.shape


(3, 478)

In [ ]:
fullx['head'].values.dim()

 # sliders

Yes, `cv2` (OpenCV) does have a built-in trackbar (slider) feature that you can use to create interactive applications. OpenCV trackbars are attached to OpenCV windows and allow you to receive a callback every time the trackbar value changes. This can be quite useful for real-time parameter tuning.

Here's an example of how you can create a trackbar using `cv2.createTrackbar()`:

```python
import cv2
import numpy as np

# The callback function that gets called when the trackbar value changes
def on_trackbar_change(coarsebuffer):
    # Here you would update your sequence with the new coarsebuffer value
    print("New coarse buffer value:", coarsebuffer)
    # Use coarsebuffer to alter the processing in the while loop below

# Create a named window
cv2.namedWindow('Frame')

# Initial value for coarsebuffer
coarsebuffer = 20

# Create a trackbar. Arguments: trackbar name, window name, value range and callback function
cv2.createTrackbar('coarse buffer', 'Frame', 0, 500, on_trackbar_change)

# Dummy image just to have something to show in the window
# You would replace this part with your video capture or sequence
dummy_frame = np.zeros((400, 400, 3), np.uint8)

while True:
    # Here you would normally process your frame and then display it
    # For demonstration, we just show the dummy_frame
    cv2.imshow('Frame', dummy_frame)

    # Check for trackbar position update
    coarsebuffer = cv2.getTrackbarPos('coarse buffer', 'Frame')

    # Your processing logic where you would use the coarsebuffer value

    # Break the loop if 'ESC' is pressed
    if cv2.waitKey(1) == 27:
        break

# Release resources and close windows
cv2.destroyAllWindows()
```

In the example above, `on_trackbar_change` is a callback function that's called when you move the slider. It receives the current value of the slider (in this case, `coarsebuffer`). Use `cv2.getTrackbarPos()` to get the current position of the trackbar if needed.

With your sequence of processing steps, integrate the `coarsebuffer` variable into the logic that happens within the loop. Note, however, that OpenCV does not support sliding interactions while the program is waiting at `cv2.waitKey()`; it's only responsive when OpenCV is processing window events.

Remember, you should handle the actual control and reading from the trackbar properly if the processing inside the loop is time-consuming to ensure a smooth UI experience.

In [ ]:
# import matplotlib.pyplot as plt

# from matplotlib.widgets import Button, Slider


# # The parametrized function to be plotted
# def f(t, amplitude, frequency):
#     return amplitude * np.sin(2 * np.pi * frequency * t)

# t = np.linspace(0, 1, 1000)

# # Define initial parameters
# init_amplitude = 5
# init_frequency = 3

# # Create the figure and the line that we will manipulate
# fig, ax = plt.subplots()
# line, = ax.plot(t, f(t, init_amplitude, init_frequency), lw=2)
# ax.set_xlabel('Time [s]')

# # adjust the main plot to make room for the sliders
# fig.subplots_adjust(left=0.25, bottom=0.25)

# # Make a horizontal slider to control the frequency.
# axfreq = fig.add_axes([0.25, 0.1, 0.65, 0.03])
# cbuffslider = Slider(
#     ax=axfreq,
#     label='coarse buffer',
#     valmin=0,
#     valmax=500,
#     valinit=init_frequency,
# )

# # Make a vertically oriented slider to control the amplitude
# axamp = fig.add_axes([0.1, 0.25, 0.0225, 0.63])
# amp_slider = Slider(
#     ax=axamp,
#     label="Amplitude",
#     valmin=0,
#     valmax=10,
#     valinit=init_amplitude,
#     orientation="vertical"
# )


# # The function to be called anytime a slider's value changes
# def update(val):
#     coarsebuffer = cbuffslider.val
#     print('cooarse buff',coarsebuffer)

# # register the update function with each slider
# cbuffslider.on_changed(update)
# amp_slider.on_changed(update)

# Create a `matplotlib.widgets.Button` to reset the sliders to initial values.
# resetax = fig.add_axes([0.8, 0.025, 0.1, 0.04])
# button = Button(resetax, 'Reset', hovercolor='0.975')


# def reset(event):
#     freq_slider.reset()
#     amp_slider.reset()
# button.on_clicked(reset)

# plt.show()

In [ ]:
import cv2
import mediapipe as mp
from pathlib import Path
import pandas as pd, numpy as np
import  xarray as xr
import pyautogui
from pyautogui import moveTo
pyautogui.FAILSAFE = False
from pathlib import Path
import numpy as np

webcam = cv2.VideoCapture(0, cv2.CAP_DSHOW)

camx,camy = 1920,1080
webcam.set(cv2.CAP_PROP_FRAME_WIDTH, camx )
webcam.set(cv2.CAP_PROP_FRAME_HEIGHT, camy)

xcenter=int(camx/2)
ycenter=660
yoffset = 325
xoffset = 450

resx,resy = pyautogui.size()
screen_w, screen_h = resx,resy

pth = Path.cwd().parent/'data'
pth.mkdir(parents=True,exist_ok=True)

face_mesh = mp.solutions.face_mesh.FaceMesh(refine_landmarks=True)

for tri in range(50):
    _, frame = webcam.read()
    if frame is not None:
        break
else:
    assert False, 'ERROR, could not init webcam! make sure the permissions are on in settings, and a webcam is active'

def oldsnapnoxr(plotface=True):
# while True:
    shaep = (478,3) # 3D , 478 landmarks from mp
    _, frame = webcam.read()

    frame = frame[ycenter-yoffset:ycenter+yoffset,xcenter-xoffset:xcenter+xoffset]
    frame = cv2.flip(frame, 1)
    rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    output = face_mesh.process(rgb_frame)
    landmark_points = output.multi_face_landmarks
    frame_h, frame_w, _ = frame.shape

    if landmark_points:
        landmarks = landmark_points[0].landmark

        # print('len',len(landmarks))
        pts = np.array([[landmark.x,landmark.y,landmark.z] for landmark in landmarks])
        assert pts.shape==shaep, pts.shape

        if plotface:
            for id, landmark in enumerate(landmarks):
                x = int(landmark.x * frame_w)
                y = int(landmark.y * frame_h)
                cv2.circle(frame, (x, y), 3, (0, 255, 0))
            cv2.imshow('ur face', frame)
            cv2.waitKey(1)
    else:
        pts = -np.ones( shaep )
    
    # pts = xr.DataArray(pts,dims=('mark','crd'))
    # assert len(pts['crd'])==3
    # pts['crd'] = ['x','y','z']
    return pts

def getxyz0(da):
    xyz0 = xr.concat([
        da.mean(dim=['s','mark']).sel(crd=['x','y']) ,
        da.min(dim=['s','mark']).sel(crd=['z'])
    ],dim='crd')
    return xyz0

def snap(plotface=True,plottext=None):
# while True:
    shaep = (478,3) # 3D , 478 landmarks from mp
    _, frame = webcam.read()

    frame = frame[ycenter-yoffset:ycenter+yoffset,xcenter-xoffset:xcenter+xoffset]
    frame = cv2.flip(frame, 1)
    rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    output = face_mesh.process(rgb_frame)
    landmark_points = output.multi_face_landmarks
    frame_h, frame_w, _ = frame.shape

    if landmark_points:
        landmarks = landmark_points[0].landmark

        # print('len',len(landmarks))
        pts = np.array([[landmark.x,landmark.y,landmark.z] for landmark in landmarks])
        assert pts.shape==shaep, pts.shape

        # eye pos ----
        # pupl = 473
        # L = 398
        # R = 263
        # lt,rt,pupil = [
        #     np.array([landmarks[idx].x,landmarks[idx].y]) for idx in (L,R,pupl) ]
        # og = np.mean((lt,rt), axis=0)
        # w = rt[0] - lt[0]
        # h = w*resy/resx # your eye given same aspect ratio of screen
        # # posnorm between -1:1 for x and y if you could move your eye all the way to the edge
        # posnorm = pupil - og
        # posnorm[0] = posnorm[0]/(2*w)
        # posnorm[1] = posnorm[1]/(2*h)
        # -----------

        if plotface:
            for id, landmark in enumerate(landmarks):
                x = int(landmark.x * frame_w)
                y = int(landmark.y * frame_h)
                cv2.circle(frame, (x, y), 3, (0, 255, 0))
            if plottext:
                frame = cv2.putText(frame, plottext,
                    #  org, font,  
                #    fontScale, color, thickness, cv2.LINE_AA
                   ) 
            cv2.imshow('ur face', frame)
            cv2.waitKey(1)
    else:
        pts = -np.ones( shaep )

    pts = xr.DataArray(pts,dims=('mark','crd'))
    assert len(pts['crd'])==3
    pts['crd'] = ['x','y','z']
    return pts

            # if id == 1:
            #     screen_x = screen_w * landmark.x
            #     screen_y = screen_h * landmark.y
            #     pyautogui.moveTo(screen_x, screen_y)
        # left = [landmarks[145], landmarks[159]]
        # for landmark in left:
        #     x = int(landmark.x * frame_w)
        #     y = int(landmark.y * frame_h)
        #     cv2.circle(frame, (x, y), 3, (0, 255, 255))
        # if (left[0].y - left[1].y) < 0.004:
        #     pyautogui.click()
        #     pyautogui.sleep(1)
    # cv2.imshow('Eye Controlled Mouse', frame)
    # cv2.waitKey(1)


import random


def listEqual(alist):
    '''returns True if every item in alist iterable is equal'''
    return all(alist[i+1] == alist[0] for i in range(len(alist)-1))


def gather(nlines = 12,npts = 25,dt=0.05,margin=5):
    '''margin: px on edge of screen to leave out'''
    caption = 'Follow the mouse with your gaze until complete'

    data = []

    xrng = np.linspace(0+margin,resx-margin,npts)
    # start from bottom to avoid neck strain
    for y in np.linspace(0+margin,resy-margin,nlines)[::-1]:
        moveTo(xrng[0],y,1)
        for x in xrng:
            moveTo(x,y,dt,_pause=False)
            data += [ (snap(True,caption) , np.array([x,y])) ]
        xrng = xrng[::-1]

    yrng = np.linspace(0+margin,resx-margin,npts)
    for x in np.linspace(0+margin,resx-margin,npts):
        moveTo(x,yrng[0],dt*3)
        for y in yrng:
            moveTo(x,y,dt,_pause=False)
            data += [ (snap() , np.array([x,y])) ]
        yrng = yrng[::-1]

    # print(data)

    # shuffling train + test
    random.shuffle(data)
    # cutoff = int(len(data)*.8)
    # train,test = data[:cutoff],data[cutoff:]

    assert listEqual([d[0].shape for d in data]), [d[0].shape for d in data]

    fullx = xr.concat([d[0] for d in data],dim='s')
    fully = np.stack([d[1] for d in data])

    # trainx = np.stack([d[0] for d in train])
    # trainy = np.stack([d[1] for d in train])
    
    # testx = np.stack([d[0] for d in test])
    # testy = np.stack([d[1] for d in test])

    print(f'BOUNCING TO {pth}')

    # np.save(pth/'fullx.npy', fullx)
    # np.save(pth/'fully.npy', fully)
    dimz = ('s','mark','crd')

    # fullx = xr.DataArray(fullx,dims=dimz)
    # fullx['crd'] = ['x','y','z']
    #  # transform to put the origin on the mean face pt position xy, and the closest depth
    #  this array of 3 pts may be calibrated to new user/position
    #  this is part of preprocessing before fed to model
    #  # will need to be further scaled for keras but OK
    xyz0 = getxyz0(fullx)
    normx = fullx - xyz0
    normx
    # only for training data:
    assert all(np.isclose(
        normx.mean(dim=['s','mark']).sel(crd=['x','y']).values,
        np.array([0,0])
    )), normx.mean(dim=['s','mark']).sel(crd=['x','y'])
    assert np.isclose( normx.min(dim=['s','mark']).sel(crd=['z']).values[0] , 0 ), \
        normx.min(dim=['s','mark']).sel(crd=['z'])

    assert fully.shape[-1]==2, f'should represent mouse x,y. hsape: {fully.shape}'
    fully = xr.DataArray(fully,dims = ('s','pos'))
    fully
    fully.name = 'mouse'
    fully = fully.to_dataset()
    fully
    normx.name = 'head'
    normx = normx.to_dataset()
    fullxy = xr.merge([normx,fully])
    fullxy
    fullxy.to_netcdf(pth/'fullxy.nc')
    print('done!')
    return fullxy
    # np.save(pth/'trainx.npy', trainx)
    # np.save(pth/'trainy.npy', trainy)
    # np.save(pth/'testx.npy', testx)
    # np.save(pth/'testy.npy', testy)

if __name__=='__main__':
    gather()

webcam.release()
cv2.destroyAllWindows()
